### ISSUE TITLE
LightTunnel android apk

### ISSUE THREAD

**Issue by ingnelson** [tuuzed/LightTunnel#7]
Hello.

Are you going to create a Android apk  to use it in our device ? 
if the answer is yes .

LightTunnel can use GET method to create the tunnel between the client (Android) and the server VPS ? 

I will wait your answer.

**Comment by tuuzed** [comment]
The LightTunnel client for Android is currently under development, and it is expected that the first beta version will be launched soon!

**Comment by ingnelson** [comment]
@tuuzed Let me know when apk is launched , please . 
I would like to test it and give some ideas ones i try it.

**Comment by tuuzed** [comment]
You can edit the HTTP request and return the HTTP response by implementing the [`lighttunnel.openapi.http.HttpTunnelRequestInterceptor`](https://github.com/tuuzed/LightTunnel/blob/master/core/server/src/main/kotlin/lighttunnel/openapi/http/HttpTunnelRequestInterceptor.kt) interface

**Comment by ingnelson** [comment]
@tuuzed i am not a programmer , i will wait for the APk . How many days do you think it will be ready for test it. ?

**Comment by tuuzed** [comment]
The first beta has been released. [https://github.com/tuuzed/LightTunnelForAndroid](https://github.com/tuuzed/LightTunnelForAndroid)

**Comment by ingnelson** [comment]
@tuuzed can you give me the command to install LightTunnel on my UBUNTU VPS ?
and the commnad to run LightTunnel on with HTTP on port 80 , please?

i am a newbie.

I will wait your response

**Comment by tuuzed** [comment]
Lighttunnel service has been deployed on the VPS provided by you. Now you can download Android App [here](https://github.com/tuuzed/LightTunnelForAndroid) test and trial

**Comment by ingnelson** [comment]
@tuuzed how configure the APK ?
If my server IP is : 172.245.22.211

I see on the VPS The you open port 8080 , 5443 , 5080, 5081.

![Screenshot_2020-07-27-14-00-32-929_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/88586673-f1532180-d011-11ea-9b3a-3dea67895717.jpg)

How to configure the APK ? Can you send me a screenshot or what to write on each option ? 

![Screenshot_2020-07-27-13-59-47-485_com tuuzed android lighttunnel](https://user-images.githubusercontent.com/6626845/88586826-35462680-d012-11ea-9ced-98e521be1708.jpg)

I will wait for you.

**Comment by tuuzed** [comment]
The TCP type tunnel can be configured in this way. The HTTP type tunnel needs to have a domain name and resolve the domain name to `172.245.22.211`.

**Comment by ingnelson** [comment]
@tuuzed I can't make it works . 
Can you give me  a screenshot how it should be configurate the app using 172.245.22.211 and port 8080 ?  I tried like this but it doesn't connect or stablish a connection: 
![Screenshot_2020-07-31-11-13-22-557_com tuuzed android lighttunnel](https://user-images.githubusercontent.com/6626845/89060038-80687e00-d31f-11ea-9196-6b1dd22876fc.jpg)

**Comment by tuuzed** [comment]
![image](https://user-images.githubusercontent.com/11827431/89091519-f7178100-d3dc-11ea-998f-c8c739b133c9.png)

**Comment by ingnelson** [comment]
@tuuzed the app says connected ,but if i open the website www.whatismyip.com it shows my ISP ip and not my vps ip.

So i think the app it is not creating a the tunnel , and it expose my ISP ip.

**Comment by tuuzed** [comment]
@ingnelson I think the purpose of your application is wrong. The purpose of this application is to expose the intranet service and bring it to the external network. 

Similar applications are [frp](https://github.com/fatedier/frp)、[ngrok](https://ngrok.com/).
