### ISSUE TITLE
LightTunnel tutorial

### ISSUE THREAD

**Issue by ingnelson** [tuuzed/LightTunnel#8]
Hello.

can you give me the commands to install LightTunnel on my UBUNTU VPS , please? 
I want to use the HTTP tunnel on port 80.

My VPS is : 
ip : 172.245.22.211
user: root
pass: matador

I really like to test it.

**Comment by tuuzed** [comment]
Thank you very much for your willingness to test. The lighttunnel service has been deployed on your VPS.
The following is the content of the service configuration file,
```ini
[basic]
bind_port = 5080
ssl_bind_port = 5443
allow_ports = 10000,10001,10002-50000
http_port = 8080
http_rpc_port = 5081
http_rpc_username = lts
http_rpc_password = lts
```
